apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  template: # This is the pod template
    metadata:
      labels:
        app: flask-app # Changed from run: flask-app to match selector
    spec:
      containers:
        - name: flask
          image: bokoness/flask-app:latest
          ports:
            - containerPort: 5000
          env:
            - name: ENV_VAR_NAME
              value: "value"
          resources: # Correctly nested under resources
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
