apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  template: # This is the pod template
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask
          image: bokoness/flask-app:latest
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          env:
            - name: FLASK_PORT
              valueFrom:
                configMapKeyRef:
                  name: flask-app-config
                  key: app_port
          livenessProbe:
            httpGet:
              path: /health # Health check endpoint
              port: 5000
            initialDelaySeconds: 5 # How long to wait after the container starts before running the first probe
            periodSeconds: 10 # How often to perform the probe
          readinessProbe:
            httpGet:
              path: /ready
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
