apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: flask-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1 #The API version of the target resource.
    kind: Deployment # The type of resource to scale (in this case, a Deployment).
    name: flask-app-deployment
  minReplicas: 1 # Minimum number of replicas to scale down to.
  maxReplicas: 5 # Maximum number of replicas to scale up to.
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50 # The HPA will aim to keep the average CPU utilization across all pods at or below 50%.
